on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build2:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build V2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Levinson Left)
        run: west build -s zmk/app -b nice_nano_v2 -- -DSHIELD=levinson_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Levinson DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano_v2.dts.pre.tmp
      - name: Levinson Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 levinson_left_nice_nano_v2.uf2
      - name: Archive (Levinson Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware_v2
          path: levinson_left_nice_nano_v2.uf2
      - name: West Build (Levinson Right)
        run: west build --pristine -s zmk/app -b nice_nano_v2 -- -DSHIELD=levinson_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Levinson Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 levinson_right_nice_nano_v2.uf2
      - name: Archive (Levinson Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware_v2
          path: levinson_right_nice_nano_v2.uf2
  build1:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build V1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (Levinson Left)
        run: west build -s zmk/app -b nice_nano -- -DSHIELD=levinson_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Levinson DTS File
        if: ${{ always() }}
        run: cat -n build/zephyr/nice_nano.dts.pre.tmp
      - name: Levinson Left Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 levinson_left_nice_nano.uf2
      - name: Archive (Levinson Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware_v1
          path: levinson_left_nice_nano.uf2
      - name: West Build (Levinson Right)
        run: west build --pristine -s zmk/app -b nice_nano -- -DSHIELD=levinson_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Levinson Right Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 levinson_right_nice_nano.uf2
      - name: Archive (Levinson Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware_v1
          path: levinson_right_nice_nano.uf2
